// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_date.proto

package top.alexmmd.grpc.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.alexmmd.grpc.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverDate = 1;</code>
   * @return The serverDate.
   */
  String getServerDate();
  /**
   * <code>string serverDate = 1;</code>
   * @return The bytes for serverDate.
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
